name: GitHub Actions Learning

on:
  push:
    branches:
      - main

jobs:
  learning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Check Linux Version
        run: uname -a

      - name: Hello Message
        run: echo "Hello Vijay! I am learning GitHub Actions."
